-- MySQL Script generated by MySQL Workbench
-- Sat Aug 27 09:48:12 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema desktop_research
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema desktop_research
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `desktop_research` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ;
USE `desktop_research` ;

-- -----------------------------------------------------
-- Table `desktop_research`.`repository_language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desktop_research`.`repository_language` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `language` VARCHAR(10) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `desktop_research`.`repository_dependency`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desktop_research`.`repository_dependency` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dependency` VARCHAR(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `desktop_research`.`repository`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desktop_research`.`repository` (
  `id` INT UNSIGNED NOT NULL,
  `name_with_owner` VARCHAR(120) NULL,
  `stars` MEDIUMINT(7) UNSIGNED NULL,
  `created_at` DATE NULL,
  `repository_language_id` INT UNSIGNED NOT NULL,
  `repository_dependency_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nameWithOwner_UNIQUE` (`name_with_owner` ASC) VISIBLE,
  INDEX `fk_repository_repository_language_idx` (`repository_language_id` ASC) VISIBLE,
  INDEX `fk_repository_repository_dependency1_idx` (`repository_dependency_id` ASC) VISIBLE,
  CONSTRAINT `fk_repository_repository_language`
    FOREIGN KEY (`repository_language_id`)
    REFERENCES `desktop_research`.`repository_language` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_repository_repository_dependency1`
    FOREIGN KEY (`repository_dependency_id`)
    REFERENCES `desktop_research`.`repository_dependency` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `desktop_research`.`repository_description`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desktop_research`.`repository_description` (
  `id` INT NOT NULL,
  `word` VARCHAR(50) NULL,
  `repository_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_repository_description_repository1_idx` (`repository_id` ASC) VISIBLE,
  CONSTRAINT `fk_repository_description_repository1`
    FOREIGN KEY (`repository_id`)
    REFERENCES `desktop_research`.`repository` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `desktop_research`.`repository_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desktop_research`.`repository_tag` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tag` VARCHAR(30) NULL,
  `repository_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_repository_tag_repository1_idx` (`repository_id` ASC) VISIBLE,
  CONSTRAINT `fk_repository_tag_repository1`
    FOREIGN KEY (`repository_id`)
    REFERENCES `desktop_research`.`repository` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
