-- MySQL Script generated by MySQL Workbench
-- Sun Sep 18 19:54:40 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema desktop_research
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema desktop_research
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `desktop_research` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ;
USE `desktop_research` ;

-- -----------------------------------------------------
-- Table `desktop_research`.`repository_language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desktop_research`.`repository_language` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `language` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `language_UNIQUE` (`language` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `desktop_research`.`repository_dependency`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desktop_research`.`repository_dependency` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dependency` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `dependency_UNIQUE` (`dependency` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `desktop_research`.`repository`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desktop_research`.`repository` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_with_owner` VARCHAR(120) NOT NULL,
  `stars` MEDIUMINT(7) UNSIGNED NOT NULL COMMENT 'for popularity',
  `created_at` DATE NOT NULL COMMENT 'for P2M1',
  `number_of_tags` TINYINT NOT NULL DEFAULT 0 COMMENT 'for P1M1',
  `full_description` TEXT NULL COMMENT 'for natural language processing and P1M1',
  `repository_language_id` INT UNSIGNED NOT NULL,
  `repository_dependency_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nameWithOwner_UNIQUE` (`name_with_owner` ASC) VISIBLE,
  INDEX `fk_repository_repository_language_idx` (`repository_language_id` ASC) VISIBLE,
  INDEX `fk_repository_repository_dependency1_idx` (`repository_dependency_id` ASC) VISIBLE,
  CONSTRAINT `fk_repository_repository_language`
    FOREIGN KEY (`repository_language_id`)
    REFERENCES `desktop_research`.`repository_language` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_repository_repository_dependency1`
    FOREIGN KEY (`repository_dependency_id`)
    REFERENCES `desktop_research`.`repository_dependency` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `desktop_research`.`repository_description`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desktop_research`.`repository_description` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `word` VARCHAR(50) NOT NULL COMMENT 'for P1M1',
  `repository_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_repository_description_repository1_idx` (`repository_id` ASC) VISIBLE,
  CONSTRAINT `fk_repository_description_repository1`
    FOREIGN KEY (`repository_id`)
    REFERENCES `desktop_research`.`repository` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `desktop_research`.`repository_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desktop_research`.`repository_tag` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tag` VARCHAR(30) NOT NULL COMMENT 'for P1M1',
  `repository_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_repository_tag_repository1_idx` (`repository_id` ASC) VISIBLE,
  CONSTRAINT `fk_repository_tag_repository1`
    FOREIGN KEY (`repository_id`)
    REFERENCES `desktop_research`.`repository` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `desktop_research`.`repository_issue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desktop_research`.`repository_issue` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `year` YEAR(4) NOT NULL COMMENT 'for P3M2',
  `open` MEDIUMINT UNSIGNED NOT NULL COMMENT 'for P3M2',
  `closed` MEDIUMINT UNSIGNED NOT NULL COMMENT 'for P3M2',
  `repository_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_repository_issue_repository1_idx` (`repository_id` ASC) VISIBLE,
  CONSTRAINT `fk_repository_issue_repository1`
    FOREIGN KEY (`repository_id`)
    REFERENCES `desktop_research`.`repository` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `desktop_research`.`repository_pull_request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desktop_research`.`repository_pull_request` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `year` YEAR(4) NOT NULL COMMENT 'P3M1',
  `open` MEDIUMINT UNSIGNED NOT NULL COMMENT 'P3M1',
  `merged` MEDIUMINT UNSIGNED NOT NULL COMMENT 'P3M1',
  `canceled` MEDIUMINT UNSIGNED NOT NULL COMMENT 'P3M1',
  `repository_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_repository_pull_request_copy1_repository1_idx` (`repository_id` ASC) VISIBLE,
  CONSTRAINT `fk_repository_pull_request_copy1_repository1`
    FOREIGN KEY (`repository_id`)
    REFERENCES `desktop_research`.`repository` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `desktop_research`.`repository_category_openia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desktop_research`.`repository_category_openia` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(50) NULL,
  `repository_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_repository_category_openia_repository1_idx` (`repository_id` ASC) VISIBLE,
  CONSTRAINT `fk_repository_category_openia_repository1`
    FOREIGN KEY (`repository_id`)
    REFERENCES `desktop_research`.`repository` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `desktop_research`.`repository_description_openia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desktop_research`.`repository_description_openia` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NULL,
  `repository_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_repository_description_openia_repository1_idx` (`repository_id` ASC) VISIBLE,
  CONSTRAINT `fk_repository_description_openia_repository1`
    FOREIGN KEY (`repository_id`)
    REFERENCES `desktop_research`.`repository` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
